"""Phase 4 – exploratory data analysis.   python ml/eda.py

Writes docs/figures/eda_*.png and docs/eda.md. All numbers in eda.md are computed here.
"""
import os
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from ml.common import FIGS, ROOT, load_data  # noqa: E402
from ml.features import RISK_LEVELS, behaviour_raw  # noqa: E402

# UI signal palette (tailwind.config.js) so figures match the app
LVL_COL = {"LOW": "#3fd08a", "MEDIUM": "#f2b53a", "HIGH": "#ff8a3d", "CRITICAL": "#ff5a52"}
INK, GRID, ASSIST = "#1d2228", "#d5dade", "#2a8ea0"
plt.rcParams.update({"font.size": 10, "axes.edgecolor": "#8a939c", "axes.grid": True, "grid.color": GRID,
                     "grid.linewidth": 0.6, "axes.spines.top": False, "axes.spines.right": False,
                     "figure.dpi": 110, "savefig.bbox": "tight"})


def save(fig, name):
    fig.savefig(os.path.join(FIGS, name)); plt.close(fig)


def main():
    os.makedirs(FIGS, exist_ok=True)
    df = load_data()
    md = ["# Exploratory data analysis", "",
          "> Synthetic prototype data — not real CAT telemetry. Generated by `python ml/eda.py`.", ""]

    # 1 ── class balance + event rate
    share = df["Safety_Risk_Level"].value_counts(normalize=True).reindex(RISK_LEVELS)
    ev = df.groupby("Safety_Risk_Level")["Safety_Event"].mean().reindex(RISK_LEVELS)
    fig, ax = plt.subplots(1, 2, figsize=(9, 3.2))
    ax[0].bar(RISK_LEVELS, share * 100, color=[LVL_COL[l] for l in RISK_LEVELS]); ax[0].set_ylabel("% of sessions")
    ax[0].set_title("Safety risk level (target)")
    ax[1].bar(RISK_LEVELS, ev * 100, color=[LVL_COL[l] for l in RISK_LEVELS]); ax[1].set_ylabel("% with safety event")
    ax[1].set_title("Observed safety events by level")
    save(fig, "eda_01_risk_levels.png")
    md += ["## 1. Target balance", "", "![](figures/eda_01_risk_levels.png)", "",
           "| Level | Share | Safety-event rate |", "|---|---|---|"]
    md += [f"| {l} | {share[l]:.1%} | {ev[l]:.1%} |" for l in RISK_LEVELS]
    md += ["", "Classes are imbalanced (HIGH and CRITICAL ≈ 10 % each), so accuracy alone is misleading. "
           "Models are compared on macro-F1 and HIGH/CRITICAL recall, and trained with class weights.", ""]

    # 2 ── proximity × speed interaction
    d = df[df["Obstacle_Type"].isin(["Worker", "Vehicle"])].copy()
    d["dist_bin"] = pd.cut(d["Proximity_Distance"], [0.5, 2, 3, 4, 6, 9, 20])
    d["speed_bin"] = pd.cut(d["Machine_Speed"], [-0.01, 1, 3, 6, 15], labels=["0–1", "1–3", "3–6", "6–15 km/h"])
    piv = d.pivot_table(index="dist_bin", columns="speed_bin", values="Safety_Risk_Score", aggfunc="mean", observed=False)
    fig, ax = plt.subplots(figsize=(6.5, 3.6))
    for i, c in enumerate(piv.columns):
        ax.plot(range(len(piv)), piv[c], marker="o", label=c, color=plt.cm.YlOrRd(0.35 + 0.2 * i))
    ax.set_xticks(range(len(piv))); ax.set_xticklabels([str(x) for x in piv.index], rotation=0)
    ax.set_xlabel("Proximity to worker / vehicle (m)"); ax.set_ylabel("Mean risk index"); ax.legend(title="Speed", fontsize=8)
    ax.set_title("Proximity and speed interact")
    save(fig, "eda_02_proximity_speed.png")
    near, far = piv.iloc[0], piv.iloc[-1]
    md += ["## 2. Proximity × speed", "", "![](figures/eda_02_proximity_speed.png)", "",
           f"Near a person (0.5–2 m) mean risk rises from {near.iloc[0]:.0f} (stationary) to {near.iloc[-1]:.0f} (6–15 km/h); "
           f"beyond 9 m the same speed change moves it only {far.iloc[0]:.0f} → {far.iloc[-1]:.0f}. "
           "The effect of speed depends on distance, so a purely additive model will underfit. Two remedies were compared in "
           "Phase 5: tree ensembles, and a linear model with explicit hazard-product terms (proximity × speed, slope × load, …). "
           "The linear model with interactions won on validation – see `ml_methodology.md` for why, and for the caveat.", ""]

    # 3 ── scenario vs risk
    order = df.groupby("Scenario")["Safety_Risk_Score"].median().sort_values().index
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.boxplot([df.loc[df["Scenario"] == s, "Safety_Risk_Score"] for s in order], vert=False, showfliers=False,
               patch_artist=True, boxprops=dict(facecolor="#e3e8ec"), medianprops=dict(color=INK))
    ax.set_yticks(range(1, len(order) + 1)); ax.set_yticklabels([s.replace("_", " ").title() for s in order], fontsize=8)
    for x, l in zip([30, 55, 75], ["MED", "HIGH", "CRIT"]):
        ax.axvline(x, color="#8a939c", ls="--", lw=0.8); ax.text(x + 0.5, len(order) + 0.3, l, fontsize=7, color="#5a6571")
    ax.set_xlabel("Safety risk index"); ax.set_title("Risk by generator scenario (latent — not a model feature)")
    save(fig, "eda_03_scenarios.png")
    md += ["## 3. Scenarios", "", "![](figures/eda_03_scenarios.png)", "",
           "Scenarios separate clearly in risk, but `Scenario` is a latent generator variable and is **never** a model input. "
           "It is used only to stratify error analysis.", ""]

    # 4 ── personal idle baselines
    b = behaviour_raw(df)
    norm = df["Operator_Anomaly"] == 0
    med = b.loc[norm, "idle_per_2h"].groupby(df.loc[norm, "Operator_ID"]).median().sort_values()
    pick = list(med.index[np.linspace(0, len(med) - 1, 10).astype(int)])
    if "OP1007" not in pick:
        pick[4] = "OP1007"
    pick = sorted(pick, key=lambda o: med[o])
    fig, ax = plt.subplots(figsize=(8, 3.6))
    ax.boxplot([b.loc[norm & (df["Operator_ID"] == o), "idle_per_2h"] for o in pick], showfliers=False, patch_artist=True,
               boxprops=dict(facecolor="#e3e8ec"), medianprops=dict(color=INK))
    an = df["Anomaly_Reason"] == "Excessive_Idle"
    for i, o in enumerate(pick, 1):
        y = b.loc[an & (df["Operator_ID"] == o), "idle_per_2h"]
        ax.scatter(np.full(len(y), i) + np.random.default_rng(0).uniform(-.15, .15, len(y)), y, s=9, color=LVL_COL["CRITICAL"], zorder=3)
    ax.set_xticklabels(pick, rotation=35, fontsize=8); ax.set_ylabel("Idle (min per 2 h)")
    ax.set_title("Normal idle differs by operator (boxes); red = sessions labelled excessive idle")
    save(fig, "eda_04_personal_idle.png")
    lo, hi = med.quantile(0.1), med.quantile(0.9)
    overlap = (b.loc[an, "idle_per_2h"] < b.loc[norm, "idle_per_2h"].quantile(0.9)).mean()
    md += ["## 4. Personal baselines (why the Digital Twin)", "", "![](figures/eda_04_personal_idle.png)", "",
           f"Operators' median normal idle ranges from {lo:.0f} to {hi:.0f} min per 2 h (10th–90th percentile of operators). "
           f"{overlap:.0%} of sessions labelled *excessive idle* fall **below** the fleet-wide 90th percentile of normal idle — "
           "a global threshold would miss them. Behaviour must be compared with the operator's own baseline.", ""]

    # 5 ── task duration
    fig, ax = plt.subplots(1, 2, figsize=(9.5, 3.4))
    for cls, col in zip(sorted(df["Machine_Model_Class"].unique()), ["#56c7db", "#2a8ea0", "#f2b53a", "#ff8a3d"]):
        s = df[df["Machine_Model_Class"] == cls].sample(600, random_state=0)
        ax[0].scatter(s["Target_Quantity"], s["Actual_Task_Duration"], s=5, alpha=0.5, color=col, label=cls)
    ax[0].set_xlabel("Target quantity (t)"); ax[0].set_ylabel("Actual duration (min)"); ax[0].legend(fontsize=7, markerscale=2)
    ratio = df["Actual_Task_Duration"] / df["Estimated_Task_Duration"]
    ax[1].hist(ratio, bins=60, color="#8a939c"); ax[1].axvline(1, color=INK, lw=1)
    ax[1].set_xlabel("Actual ÷ planner estimate"); ax[1].set_title("Planner estimate is biased and noisy", fontsize=9)
    save(fig, "eda_05_task_duration.png")
    md += ["## 5. Task duration", "", "![](figures/eda_05_task_duration.png)", "",
           f"Actual ÷ planner estimate: median {ratio.median():.2f}, 10th–90th percentile {ratio.quantile(.1):.2f}–{ratio.quantile(.9):.2f}. "
           "The planner ignores operator skill, terrain, weather and machine health, which the regression model can use.", ""]

    # 6 ── correlations
    cols = ["Proximity_Distance", "Machine_Speed", "Ground_Slope", "Load_Percentage", "Visibility", "Blind_Zone_Entry",
            "Control_Smoothness", "Machine_Health_Score", "Engine_Temperature", "Operator_Skill_Score", "Safety_Risk_Score"]
    c = df[cols].corr(method="spearman")
    fig, ax = plt.subplots(figsize=(7, 6))
    im = ax.imshow(c, cmap="RdBu_r", vmin=-1, vmax=1)
    ax.set_xticks(range(len(cols))); ax.set_xticklabels([x.replace("_", " ") for x in cols], rotation=60, ha="right", fontsize=8)
    ax.set_yticks(range(len(cols))); ax.set_yticklabels([x.replace("_", " ") for x in cols], fontsize=8)
    for i in range(len(cols)):
        for j in range(len(cols)):
            ax.text(j, i, f"{c.iloc[i, j]:.2f}", ha="center", va="center", fontsize=6)
    ax.grid(False); fig.colorbar(im, fraction=0.04); ax.set_title("Spearman correlation")
    save(fig, "eda_06_correlation.png")
    top = c["Safety_Risk_Score"].drop("Safety_Risk_Score").abs().sort_values(ascending=False)
    md += ["## 6. Correlation", "", "![](figures/eda_06_correlation.png)", "",
           "Strongest single-feature association with the risk index: " +
           ", ".join(f"{k.replace('_', ' ')} (|ρ| {v:.2f})" for k, v in top.head(4).items()) +
           ". No single feature exceeds |ρ| 0.5, i.e. risk emerges from combinations of factors.", ""]

    md += ["## 7. Feature-engineering decisions", "",
           "| Feature | Why |", "|---|---|",
           "| `Inv_Proximity` = 1 / distance | risk grows sharply as distance → 0; helps the linear baseline |",
           "| `Person_Nearby` | a structure at 2 m is not a worker at 2 m |",
           "| `Is_Reversing`, `Seatbelt_Off` | binary flags from categorical sensor states |",
           "| `Harsh_Rate_per_h` | counts scale with duration; the rate is comparable across sessions (a rolling rate at run time) |",
           "| `Remaining_Quantity`, `Planner_Remaining`, `Historical_Remaining` | progress-adjusted versions of known plan quantities for the remaining-time model |",
           "| behaviour rates + context-expected speed / fuel | anomaly model compares behaviour to the operator's own baseline after removing terrain, load and machine-class effects |",
           "", "Leakage exclusions per model are enforced in code (`ml/features.py` `*_FORBIDDEN`, asserted by tests)."]
    with open(os.path.join(ROOT, "docs", "eda.md"), "w") as f:
        f.write("\n".join(md) + "\n")
    print("\n".join(md[:0]) or "wrote docs/eda.md and 6 figures")


if __name__ == "__main__":
    main()
